---
- name: Create API Token
  jenkins_script:
    script: "{{ lookup('file', 'files/create_api_token.groovy') }}"
    user: admin
    password: "{{ jenkins_admin_password }}"
  register: api_result

- set_fact:
    jenkins_token: "{{ api_result.output | replace('Result:' ,'') | trim }}"

- name: create seed job
  jenkins_job:
    config: "{{ lookup('template', jenkins_seed_template) }}"
    name: "{{ jenkins_seed_name }}"
    token: "{{ jenkins_token }}"
    url: http://localhost:8080
    user: admin

- name: Run seed job
  uri:
    user: admin
    password: "{{ jenkins_token }}"
    force_basic_auth: yes
    url: "http://127.0.0.1:8080/job/{{ jenkins_seed_name }}/build"
    method: POST
    status_code: 201
  register: jenkins_seed_job_started

- name: Wait for seed job
  uri:
    user: admin
    password: "{{ jenkins_admin_password }}"
    force_basic_auth: yes
    url: "http://127.0.0.1:8080/job/{{ jenkins_seed_name }}/lastBuild/buildNumber?token={{ jenkins_token }}"
    method: GET
    status_code: 200
  register: jenkins_seed
  until: jenkins_seed['status']|default(0) == 200
  retries: 10
  delay: 5
